#!/bin/sh

netif_create() {

		if [ -n "$policy" ]; then
			if $policy = "802.ad"; then
	ip link add $interface type bond mode ${policy} xmit_hash_policy layer2 lacp_rate 1 miimon 100
			else
	ip link add $interface type bond mode ${policy}
		else
			echo "policy required. Please use one of the following policies:"
			echo "active-backup, balance-rr, balance-xor, balance-tlb, balance-alb, broadcast, 802.3ad"
		fi
}

netif_destroy() {

ip link delete dev ${interface}

}
netif_pre_up() {

        for ipnm in $ipaddr $ipaddrs; do
                ip addr add $ipnm dev $interface || die "Couldn't add $ipnm to $interface"
        done
        for ipnm6 in $ipaddr6 $ipaddrs6; do
                ip -6 addr add $ipnm6 dev $interface || die "Couldn't add $ipnm6 to $interface"
        done
}

netif_post_up() {
    require slaves
	local slave
    local bcast
     if [ -n "$slaves" ]; then
         for slave in ${slaves//netif./}; do
        ip link set ${slave} down
        ip link set ${slave} master ${interface}
			done
		fi

}

netif_pre_down() {
	local slave
    local bcast
     if [ -n "$slaves" ]; then
         for slave in ${slaves//netif./}; do
        ip link set ${slave} nomaster
		ip link set ${slave} down
			done
		fi
}
